### PR TITLE
Leaflet v1.0.0

### PR DESCRIPTION
**Pull request by mejackreed**
_Update 2016-09-27_ recently updated to support Leaflet v1.0.0 release

### CODE REVIEW

**Comment by eliotjordan** [comment]
I just gave this a spin, both before and after rebasing. The new version Leaflet creates some strange artifacts when zooming. I gather there are a lot of breaking changes in the update.

artifacts

**Comment by mejackreed** [comment]
Yep, I think this artifact issue was introduced in this PR: https://github.com/mejackreed/Leaflet-IIIF/pull/22

**Comment by eliotjordan** [comment]
I see. Yep, the artifacts appear in the current Leaflet version as well ( < 1.0 ). Should this commit be reverted? Do you know the reasoning behind it? There isn't much narrative on the PR.

**Comment by mejackreed** [comment]
Artifact issue now fixed in #27

**Comment by mejackreed** [comment]
Updated to work with Leaflet v.1.0.0 released today. Question: do we need to maintain backwards compatibility?

**Comment by eliotjordan** [comment]
Not sure. I guess it depends on how difficult it is to implement vs. the needs of existing users. In terms of leaflet-iiif for Geoblacklight:

- `leaflet-rails` is currently at `v1.0.0.pre.rc1`. I would imagine this PR is compatible and they will update the gem soon.
- `esri-leaflet` is the same story. We'll need to upgrade to version 2.x.

Some simple updates to GeoBlacklight are all that are involved here.

**Comment by mejackreed** [comment]
@eliotjordan that works for GeoBlacklight, I'm also concerned about other adopters who may need to still work with Leaflet 0.7.x.

**Pull request merged**
